name: CI Build and Run janetfilter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '23'

    - name: Clone janetfilter repository
      run: |
        git clone https://github.com/offsoc/janetfilter.git
        cd janetfilter

    - name: Go offline with Maven dependencies
      run: |
        cd janetfilter
        ./mvnw dependency:go-offline

    - name: Clean and install without tests
      run: |
        cd janetfilter
        ./mvn clean package
        
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: signal-server-artifacts
        path: Signal-Server/service/target/*.jar 
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: websocket-resources-artifacts
        path: Signal-Server/websocket-resources/target/*.jar 

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name:  api-doc-artifacts
        path: Signal-Server/api-doc/target/*.jar 

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name:  integration-tests-artifacts
        path: Signal-Server/integration-tests/target/*.jar 


  
